export const IconConfig = {
  home: 'home',
  favorites: 'star',
  back: 'arrow-back',
  search: 'search',
  close: 'close',
  starEmpty: 'star-outline',
  starFilled: 'star',
  location: 'location',
  business: 'business',
  globe: 'globe',
  calendar: 'calendar',
  refresh: 'refresh',
  repositories: 'folder',
  followers: 'users',
  following: 'user-plus',
  loading: 'reload',
  error: 'warning',
  empty: 'search',
  retry: 'refresh',
  sortAsc: 'arrow-up',
  sortDesc: 'arrow-down',
} as const;
